CREATE TABLE asteroid_risk_raw (
    window_start TIMESTAMP,
    window_end TIMESTAMP,
    asteroid_full_name TEXT,
    hazardous_flag BOOLEAN,
    size_kpi TEXT,
    mach_kpi DOUBLE PRECISION,
    risk_score INTEGER,
    diameter_min_km_avg DOUBLE PRECISION,
    diameter_max_km_avg DOUBLE PRECISION,
    diameter_avg_km_avg DOUBLE PRECISION,
    eccentricity_avg DOUBLE PRECISION,
    semi_major_axis_au_avg DOUBLE PRECISION,
    inclination_deg_avg DOUBLE PRECISION,
    orbital_period_days_avg DOUBLE PRECISION,
    perihelion_distance_au_avg DOUBLE PRECISION,
    velocity_km_s_avg DOUBLE PRECISION,
    miss_distance_km_avg DOUBLE PRECISION,
    inserted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);